version: '3'

services:
  php:
    build:
      context: .
      dockerfile: php-8.1.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
  php8.2:
    build:
      context: .
      dockerfile: php-8.2.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
  php8.3:
    build:
      context: .
      dockerfile: php-8.3.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
