name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - lowest
          - highest
        platform-reqs:
          - use-platform-reqs
        include:
          - php-version: "8.1"
            dependencies: highest
            platform-reqs: ignore-platform-reqs
          - php-version: "8.1"
            dependencies: lowest
            platform-reqs: ignore-platform-reqs

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install lowest dependencies
        if: ${{ matrix.dependencies == 'lowest' && matrix.platform-reqs == 'use-platform-reqs' }}
        run: composer update --no-interaction --prefer-lowest

      - name: Install lowest dependencies (ignore platform reqs)
        if: ${{ matrix.dependencies == 'lowest' && matrix.platform-reqs == 'ignore-platform-reqs' }}
        run: composer update --no-interaction --prefer-lowest --ignore-platform-reqs

      - name: Install highest dependencies
        if: ${{ matrix.dependencies == 'highest' && matrix.platform-reqs == 'use-platform-reqs' }}
        run: composer update --no-interaction

      - name: Install highest dependencies (ignore platform reqs)
        if: ${{ matrix.dependencies == 'highest' && matrix.platform-reqs == 'ignore-platform-reqs' }}
        run: composer update --no-interaction --ignore-platform-reqs

      - name: Build tables
        run: composer build

      - name: Run tests
        run: composer test

      - name: Run Infection
        run: composer infection
